const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{test}=require('node:test');
const {validateSnapshot,validateEventSnapshot,validateKamiparaDashboard,sha256}=require('../tools/detail-snapshot-lib.cjs');
const {validateMemberAnalytics}=require('../tools/member-analytics-lib.cjs');
const revision='sha256-de25812203433bf07d2e23ca203816b1cb033eed1eb723cd223a1362fef865cd';
const dataRevision='sha256-ae60c8e521edbb636f1c3a584736413ea697f661603ebe14208acc4a4dadf968';
const snapshots=path.join(__dirname,'../data/snapshots'),root=path.join(snapshots,revision);
function fixture(){return JSON.parse(fs.readFileSync(path.join(snapshots,'sha256-c7349aa942952a64088e1df95e62cc81f7f42655785b9826c36badc06e89caa4/events/EV0348.json')));}
function validate(w){return validateEventSnapshot('EV0348',w,w.snapshot.revision,w.snapshot.dataRevision);}
test('legacy missing relativePosition remains valid',()=>{const w=fixture();delete w.data.event.songs[0].relativePosition;assert.doesNotThrow(()=>validate(w));});
test('relativePosition null remains valid',()=>{const w=fixture();w.data.event.songs[0].relativePosition=null;assert.doesNotThrow(()=>validate(w));});
test('false Event can hold positive relativePosition',()=>{const w=fixture();w.data.event.songs[0].relativePosition=1;assert.doesNotThrow(()=>validate(w));});
test('relativePosition rejects non-positive / non-integer values',()=>{for(const n of [0,-1,1.5,'1',true]){const w=fixture();w.data.event.songs[0].relativePosition=n;assert.throws(()=>validate(w),/Invalid relative/);}});
test('simultaneous absolute / relative values fail',()=>{const w=fixture();Object.assign(w.data.event.songs[0],{setlistPosition:1,relativePosition:1});assert.throws(()=>validate(w),/Conflicting/);});
test('relativePosition never satisfies true Event absolute completeness',()=>{const w=fixture();w.data.event.songOrderIsSetlist=true;w.data.event.songs[0].relativePosition=1;assert.throws(()=>validate(w),/missing position/);});
function generation(){const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'))),events=new Map();assert.equal(manifest.outputRevision,revision);assert.equal(manifest.dataRevision,dataRevision);assert.deepEqual(manifest.counts,{releases:114,songs:117,details:231,kamiparaDashboard:1,events:353,memberAnalytics:1});for(const [group,type,count] of [['releases','release',114],['songs','song',117],['events','event',353]]){const entries=manifest.hashes[group];assert.equal(Object.keys(entries).length,count);assert.equal(fs.readdirSync(path.join(root,group)).filter(n=>n.endsWith('.json')).length,count);for(const [id,h] of Object.entries(entries)){const body=fs.readFileSync(path.join(root,group,id+'.json'),'utf8'),w=JSON.parse(body);assert.equal(w.snapshot.outputRevision,revision);assert.equal(w.snapshot.dataRevision,dataRevision);if(type==='event')events.set(id,validateEventSnapshot(id,w,revision,dataRevision).event);else validateSnapshot(type,id,w,revision,dataRevision);assert.equal(sha256(w.data),h.sha256);assert.equal(sha256(body),h.fileSha256);assert.equal(Buffer.byteLength(body),h.bytes);}}
 for(const [filename,key,check] of [['release-list.json','releaseList',w=>assert.equal(w.data.length,114)],['kamipara-dashboard.json','kamiparaDashboard',w=>validateKamiparaDashboard(w.data,dataRevision)],['member-analytics.json','memberAnalytics',w=>validateMemberAnalytics(w.data)]]){const body=fs.readFileSync(path.join(root,filename),'utf8'),w=JSON.parse(body),h=manifest[key];assert.equal(w.snapshot.outputRevision,revision);assert.equal(w.snapshot.dataRevision,dataRevision);check(w);assert.equal(sha256(w.data),h.sha256);assert.equal(sha256(body),h.fileSha256);assert.equal(Buffer.byteLength(body),h.bytes);}return {manifest,events};}
test('v5 complete generation schema / count / file and data hashes',()=>generation());
test('all Event totals and reference integrity',()=>{const {events,manifest}=generation(),all=[...events.values()],songs=all.flatMap(e=>e.songs);assert.equal(all.filter(e=>e.songOrderIsSetlist).length,101);assert.equal(songs.length,1400);assert.equal(songs.filter(s=>s.setlistPosition!=null).length,842);assert.equal(songs.filter(s=>s.relativePosition!=null).length,6);for(const e of all){for(const s of e.songs){assert.ok(manifest.hashes.songs[s.songId]);assert.ok(s.setlistPosition==null||s.relativePosition==null);if(e.songOrderIsSetlist)assert.ok(s.setlistPosition>0);}for(const r of e.relatedReleases)assert.ok(manifest.hashes.releases[r.releaseId]);for(const n of [e.navigation.previous,e.navigation.next,...(e.navigation.events||[])])if(n)assert.ok(events.has(n.eventId));}});
test('final official representative positions and duplicate occurrence regression',()=>{const {events:m}=generation(),p=(id,k)=>m.get(id).songs.map(s=>s[k]).sort((a,b)=>a-b);for(const [id,expected] of [['EV0002',[1,2]],['EV0046',[1]],['EV0092',[1,2,3]]]){assert.equal(m.get(id).songOrderIsSetlist,false);assert.ok(m.get(id).songs.every(s=>s.setlistPosition===null));assert.deepEqual(p(id,'relativePosition'),expected);}for(const [id,start,count] of [['EV0054',16,6],['EV0055',26,6],['EV0056',23,6],['EV0057',24,6],['EV0103',11,1],['EV0274',1,5],['EV0275',1,5],['EV0299',1,5],['EV0300',1,5]]){assert.equal(m.get(id).songOrderIsSetlist,true);assert.deepEqual(p(id,'setlistPosition'),Array.from({length:count},(_,i)=>start+i));assert.ok(m.get(id).songs.every(s=>s.relativePosition===null));}assert.deepEqual(m.get('EV0001').songs.filter(s=>s.songId==='S001').map(s=>s.setlistPosition),[1,18]);assert.equal(m.get('EV0217').songs.filter(s=>s.setlistPosition===22).length,6);assert.equal(m.get('EV0218').songs.filter(s=>s.setlistPosition===18).length,6);});
